export const galleryImages: GalleryImages[] = [
    {
        id: 1,
        category: "Hair Coloring",
        title: "Vibrant Red Hair Transformation",
        before: "/assets/image-1.jpg",
        after: "/assets/image-2.jpg",
        likes: 120,
        isBeforeAfter: true,
    },
    {
        id: 2,
        category: "Nails",
        title: "Elegant French Manicure",
        before: "/assets/image-3.jpg",
        after: "/assets/image-4.jpg",
        likes: 85,
        isBeforeAfter: true,
    },
    {
        id: 3,
        category: "Bridal",
        title: "Glamorous Bridal Makeup",
        before: "/assets/image-5.jpg",
        after: "/assets/image-6.jpg",
        likes: 150,
        isBeforeAfter: true,
    },
    {
        id: 4,
        category: "Hair Styling",
        title: "Sleek Bob Haircut",
        before: "/assets/image-7.jpg",
        after: "/assets/image-8.jpg",
        likes: 95,
        isBeforeAfter: true,
    },
    {
        id: 5,
        category: "Makeup",
        title: "Smokey Eye Makeup Look",
        before: "/assets/image-9.jpg",
        after: "/assets/image-10.jpg",
        likes: 110,
        isBeforeAfter: true,
    },
    {
        id: 6,
        category: "Lash Extensions",
        title: "Dramatic Lash Extension",
        before: "/assets/image-11.jpg",
        after: "/assets/image-10.jpg",
        likes: 75,
        isBeforeAfter: true,
    }
]